# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andy/Github/My/SFulx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andy/Github/My/SFulx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy/Github/My/SFulx/CMakeFiles /home/andy/Github/My/SFulx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy/Github/My/SFulx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/GameEngine

# Build rule for target.
bin/GameEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bin/GameEngine
.PHONY : bin/GameEngine

# fast build rule for target.
bin/GameEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/build
.PHONY : bin/GameEngine/fast

src/AssetManager/AssetManager.o: src/AssetManager/AssetManager.cpp.o
.PHONY : src/AssetManager/AssetManager.o

# target to build an object file
src/AssetManager/AssetManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/AssetManager.cpp.o
.PHONY : src/AssetManager/AssetManager.cpp.o

src/AssetManager/AssetManager.i: src/AssetManager/AssetManager.cpp.i
.PHONY : src/AssetManager/AssetManager.i

# target to preprocess a source file
src/AssetManager/AssetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/AssetManager.cpp.i
.PHONY : src/AssetManager/AssetManager.cpp.i

src/AssetManager/AssetManager.s: src/AssetManager/AssetManager.cpp.s
.PHONY : src/AssetManager/AssetManager.s

# target to generate assembly for a file
src/AssetManager/AssetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/AssetManager.cpp.s
.PHONY : src/AssetManager/AssetManager.cpp.s

src/AssetManager/Lua/luaLoader.o: src/AssetManager/Lua/luaLoader.cpp.o
.PHONY : src/AssetManager/Lua/luaLoader.o

# target to build an object file
src/AssetManager/Lua/luaLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/Lua/luaLoader.cpp.o
.PHONY : src/AssetManager/Lua/luaLoader.cpp.o

src/AssetManager/Lua/luaLoader.i: src/AssetManager/Lua/luaLoader.cpp.i
.PHONY : src/AssetManager/Lua/luaLoader.i

# target to preprocess a source file
src/AssetManager/Lua/luaLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/Lua/luaLoader.cpp.i
.PHONY : src/AssetManager/Lua/luaLoader.cpp.i

src/AssetManager/Lua/luaLoader.s: src/AssetManager/Lua/luaLoader.cpp.s
.PHONY : src/AssetManager/Lua/luaLoader.s

# target to generate assembly for a file
src/AssetManager/Lua/luaLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/Lua/luaLoader.cpp.s
.PHONY : src/AssetManager/Lua/luaLoader.cpp.s

src/AssetManager/ResourceLoader.o: src/AssetManager/ResourceLoader.cpp.o
.PHONY : src/AssetManager/ResourceLoader.o

# target to build an object file
src/AssetManager/ResourceLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceLoader.cpp.o
.PHONY : src/AssetManager/ResourceLoader.cpp.o

src/AssetManager/ResourceLoader.i: src/AssetManager/ResourceLoader.cpp.i
.PHONY : src/AssetManager/ResourceLoader.i

# target to preprocess a source file
src/AssetManager/ResourceLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceLoader.cpp.i
.PHONY : src/AssetManager/ResourceLoader.cpp.i

src/AssetManager/ResourceLoader.s: src/AssetManager/ResourceLoader.cpp.s
.PHONY : src/AssetManager/ResourceLoader.s

# target to generate assembly for a file
src/AssetManager/ResourceLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceLoader.cpp.s
.PHONY : src/AssetManager/ResourceLoader.cpp.s

src/AssetManager/ResourceManager.o: src/AssetManager/ResourceManager.cpp.o
.PHONY : src/AssetManager/ResourceManager.o

# target to build an object file
src/AssetManager/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceManager.cpp.o
.PHONY : src/AssetManager/ResourceManager.cpp.o

src/AssetManager/ResourceManager.i: src/AssetManager/ResourceManager.cpp.i
.PHONY : src/AssetManager/ResourceManager.i

# target to preprocess a source file
src/AssetManager/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceManager.cpp.i
.PHONY : src/AssetManager/ResourceManager.cpp.i

src/AssetManager/ResourceManager.s: src/AssetManager/ResourceManager.cpp.s
.PHONY : src/AssetManager/ResourceManager.s

# target to generate assembly for a file
src/AssetManager/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/AssetManager/ResourceManager.cpp.s
.PHONY : src/AssetManager/ResourceManager.cpp.s

src/Input/InputHandler.o: src/Input/InputHandler.cpp.o
.PHONY : src/Input/InputHandler.o

# target to build an object file
src/Input/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Input/InputHandler.cpp.o
.PHONY : src/Input/InputHandler.cpp.o

src/Input/InputHandler.i: src/Input/InputHandler.cpp.i
.PHONY : src/Input/InputHandler.i

# target to preprocess a source file
src/Input/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Input/InputHandler.cpp.i
.PHONY : src/Input/InputHandler.cpp.i

src/Input/InputHandler.s: src/Input/InputHandler.cpp.s
.PHONY : src/Input/InputHandler.s

# target to generate assembly for a file
src/Input/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Input/InputHandler.cpp.s
.PHONY : src/Input/InputHandler.cpp.s

src/Logic/AnimatedObject.o: src/Logic/AnimatedObject.cpp.o
.PHONY : src/Logic/AnimatedObject.o

# target to build an object file
src/Logic/AnimatedObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/AnimatedObject.cpp.o
.PHONY : src/Logic/AnimatedObject.cpp.o

src/Logic/AnimatedObject.i: src/Logic/AnimatedObject.cpp.i
.PHONY : src/Logic/AnimatedObject.i

# target to preprocess a source file
src/Logic/AnimatedObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/AnimatedObject.cpp.i
.PHONY : src/Logic/AnimatedObject.cpp.i

src/Logic/AnimatedObject.s: src/Logic/AnimatedObject.cpp.s
.PHONY : src/Logic/AnimatedObject.s

# target to generate assembly for a file
src/Logic/AnimatedObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/AnimatedObject.cpp.s
.PHONY : src/Logic/AnimatedObject.cpp.s

src/Logic/GameScene.o: src/Logic/GameScene.cpp.o
.PHONY : src/Logic/GameScene.o

# target to build an object file
src/Logic/GameScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/GameScene.cpp.o
.PHONY : src/Logic/GameScene.cpp.o

src/Logic/GameScene.i: src/Logic/GameScene.cpp.i
.PHONY : src/Logic/GameScene.i

# target to preprocess a source file
src/Logic/GameScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/GameScene.cpp.i
.PHONY : src/Logic/GameScene.cpp.i

src/Logic/GameScene.s: src/Logic/GameScene.cpp.s
.PHONY : src/Logic/GameScene.s

# target to generate assembly for a file
src/Logic/GameScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/GameScene.cpp.s
.PHONY : src/Logic/GameScene.cpp.s

src/Logic/Interactable.o: src/Logic/Interactable.cpp.o
.PHONY : src/Logic/Interactable.o

# target to build an object file
src/Logic/Interactable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Interactable.cpp.o
.PHONY : src/Logic/Interactable.cpp.o

src/Logic/Interactable.i: src/Logic/Interactable.cpp.i
.PHONY : src/Logic/Interactable.i

# target to preprocess a source file
src/Logic/Interactable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Interactable.cpp.i
.PHONY : src/Logic/Interactable.cpp.i

src/Logic/Interactable.s: src/Logic/Interactable.cpp.s
.PHONY : src/Logic/Interactable.s

# target to generate assembly for a file
src/Logic/Interactable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Interactable.cpp.s
.PHONY : src/Logic/Interactable.cpp.s

src/Logic/MainMenuScene.o: src/Logic/MainMenuScene.cpp.o
.PHONY : src/Logic/MainMenuScene.o

# target to build an object file
src/Logic/MainMenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MainMenuScene.cpp.o
.PHONY : src/Logic/MainMenuScene.cpp.o

src/Logic/MainMenuScene.i: src/Logic/MainMenuScene.cpp.i
.PHONY : src/Logic/MainMenuScene.i

# target to preprocess a source file
src/Logic/MainMenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MainMenuScene.cpp.i
.PHONY : src/Logic/MainMenuScene.cpp.i

src/Logic/MainMenuScene.s: src/Logic/MainMenuScene.cpp.s
.PHONY : src/Logic/MainMenuScene.s

# target to generate assembly for a file
src/Logic/MainMenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MainMenuScene.cpp.s
.PHONY : src/Logic/MainMenuScene.cpp.s

src/Logic/MoveableObject.o: src/Logic/MoveableObject.cpp.o
.PHONY : src/Logic/MoveableObject.o

# target to build an object file
src/Logic/MoveableObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MoveableObject.cpp.o
.PHONY : src/Logic/MoveableObject.cpp.o

src/Logic/MoveableObject.i: src/Logic/MoveableObject.cpp.i
.PHONY : src/Logic/MoveableObject.i

# target to preprocess a source file
src/Logic/MoveableObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MoveableObject.cpp.i
.PHONY : src/Logic/MoveableObject.cpp.i

src/Logic/MoveableObject.s: src/Logic/MoveableObject.cpp.s
.PHONY : src/Logic/MoveableObject.s

# target to generate assembly for a file
src/Logic/MoveableObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MoveableObject.cpp.s
.PHONY : src/Logic/MoveableObject.cpp.s

src/Logic/MultiplayerClass.o: src/Logic/MultiplayerClass.cpp.o
.PHONY : src/Logic/MultiplayerClass.o

# target to build an object file
src/Logic/MultiplayerClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MultiplayerClass.cpp.o
.PHONY : src/Logic/MultiplayerClass.cpp.o

src/Logic/MultiplayerClass.i: src/Logic/MultiplayerClass.cpp.i
.PHONY : src/Logic/MultiplayerClass.i

# target to preprocess a source file
src/Logic/MultiplayerClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MultiplayerClass.cpp.i
.PHONY : src/Logic/MultiplayerClass.cpp.i

src/Logic/MultiplayerClass.s: src/Logic/MultiplayerClass.cpp.s
.PHONY : src/Logic/MultiplayerClass.s

# target to generate assembly for a file
src/Logic/MultiplayerClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/MultiplayerClass.cpp.s
.PHONY : src/Logic/MultiplayerClass.cpp.s

src/Logic/Object.o: src/Logic/Object.cpp.o
.PHONY : src/Logic/Object.o

# target to build an object file
src/Logic/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Object.cpp.o
.PHONY : src/Logic/Object.cpp.o

src/Logic/Object.i: src/Logic/Object.cpp.i
.PHONY : src/Logic/Object.i

# target to preprocess a source file
src/Logic/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Object.cpp.i
.PHONY : src/Logic/Object.cpp.i

src/Logic/Object.s: src/Logic/Object.cpp.s
.PHONY : src/Logic/Object.s

# target to generate assembly for a file
src/Logic/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Object.cpp.s
.PHONY : src/Logic/Object.cpp.s

src/Logic/Player.o: src/Logic/Player.cpp.o
.PHONY : src/Logic/Player.o

# target to build an object file
src/Logic/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Player.cpp.o
.PHONY : src/Logic/Player.cpp.o

src/Logic/Player.i: src/Logic/Player.cpp.i
.PHONY : src/Logic/Player.i

# target to preprocess a source file
src/Logic/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Player.cpp.i
.PHONY : src/Logic/Player.cpp.i

src/Logic/Player.s: src/Logic/Player.cpp.s
.PHONY : src/Logic/Player.s

# target to generate assembly for a file
src/Logic/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Player.cpp.s
.PHONY : src/Logic/Player.cpp.s

src/Logic/Projectile.o: src/Logic/Projectile.cpp.o
.PHONY : src/Logic/Projectile.o

# target to build an object file
src/Logic/Projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Projectile.cpp.o
.PHONY : src/Logic/Projectile.cpp.o

src/Logic/Projectile.i: src/Logic/Projectile.cpp.i
.PHONY : src/Logic/Projectile.i

# target to preprocess a source file
src/Logic/Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Projectile.cpp.i
.PHONY : src/Logic/Projectile.cpp.i

src/Logic/Projectile.s: src/Logic/Projectile.cpp.s
.PHONY : src/Logic/Projectile.s

# target to generate assembly for a file
src/Logic/Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Projectile.cpp.s
.PHONY : src/Logic/Projectile.cpp.s

src/Logic/Structure.o: src/Logic/Structure.cpp.o
.PHONY : src/Logic/Structure.o

# target to build an object file
src/Logic/Structure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Structure.cpp.o
.PHONY : src/Logic/Structure.cpp.o

src/Logic/Structure.i: src/Logic/Structure.cpp.i
.PHONY : src/Logic/Structure.i

# target to preprocess a source file
src/Logic/Structure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Structure.cpp.i
.PHONY : src/Logic/Structure.cpp.i

src/Logic/Structure.s: src/Logic/Structure.cpp.s
.PHONY : src/Logic/Structure.s

# target to generate assembly for a file
src/Logic/Structure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Logic/Structure.cpp.s
.PHONY : src/Logic/Structure.cpp.s

src/Renderer/Animator.o: src/Renderer/Animator.cpp.o
.PHONY : src/Renderer/Animator.o

# target to build an object file
src/Renderer/Animator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/Animator.cpp.o
.PHONY : src/Renderer/Animator.cpp.o

src/Renderer/Animator.i: src/Renderer/Animator.cpp.i
.PHONY : src/Renderer/Animator.i

# target to preprocess a source file
src/Renderer/Animator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/Animator.cpp.i
.PHONY : src/Renderer/Animator.cpp.i

src/Renderer/Animator.s: src/Renderer/Animator.cpp.s
.PHONY : src/Renderer/Animator.s

# target to generate assembly for a file
src/Renderer/Animator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/Animator.cpp.s
.PHONY : src/Renderer/Animator.cpp.s

src/Renderer/FontManager.o: src/Renderer/FontManager.cpp.o
.PHONY : src/Renderer/FontManager.o

# target to build an object file
src/Renderer/FontManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/FontManager.cpp.o
.PHONY : src/Renderer/FontManager.cpp.o

src/Renderer/FontManager.i: src/Renderer/FontManager.cpp.i
.PHONY : src/Renderer/FontManager.i

# target to preprocess a source file
src/Renderer/FontManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/FontManager.cpp.i
.PHONY : src/Renderer/FontManager.cpp.i

src/Renderer/FontManager.s: src/Renderer/FontManager.cpp.s
.PHONY : src/Renderer/FontManager.s

# target to generate assembly for a file
src/Renderer/FontManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Renderer/FontManager.cpp.s
.PHONY : src/Renderer/FontManager.cpp.s

src/Window/Game.o: src/Window/Game.cpp.o
.PHONY : src/Window/Game.o

# target to build an object file
src/Window/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Game.cpp.o
.PHONY : src/Window/Game.cpp.o

src/Window/Game.i: src/Window/Game.cpp.i
.PHONY : src/Window/Game.i

# target to preprocess a source file
src/Window/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Game.cpp.i
.PHONY : src/Window/Game.cpp.i

src/Window/Game.s: src/Window/Game.cpp.s
.PHONY : src/Window/Game.s

# target to generate assembly for a file
src/Window/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Game.cpp.s
.PHONY : src/Window/Game.cpp.s

src/Window/Window.o: src/Window/Window.cpp.o
.PHONY : src/Window/Window.o

# target to build an object file
src/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Window.cpp.o
.PHONY : src/Window/Window.cpp.o

src/Window/Window.i: src/Window/Window.cpp.i
.PHONY : src/Window/Window.i

# target to preprocess a source file
src/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Window.cpp.i
.PHONY : src/Window/Window.cpp.i

src/Window/Window.s: src/Window/Window.cpp.s
.PHONY : src/Window/Window.s

# target to generate assembly for a file
src/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/Window/Window.cpp.s
.PHONY : src/Window/Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/GameEngine.dir/build.make CMakeFiles/bin/GameEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/GameEngine"
	@echo "... src/AssetManager/AssetManager.o"
	@echo "... src/AssetManager/AssetManager.i"
	@echo "... src/AssetManager/AssetManager.s"
	@echo "... src/AssetManager/Lua/luaLoader.o"
	@echo "... src/AssetManager/Lua/luaLoader.i"
	@echo "... src/AssetManager/Lua/luaLoader.s"
	@echo "... src/AssetManager/ResourceLoader.o"
	@echo "... src/AssetManager/ResourceLoader.i"
	@echo "... src/AssetManager/ResourceLoader.s"
	@echo "... src/AssetManager/ResourceManager.o"
	@echo "... src/AssetManager/ResourceManager.i"
	@echo "... src/AssetManager/ResourceManager.s"
	@echo "... src/Input/InputHandler.o"
	@echo "... src/Input/InputHandler.i"
	@echo "... src/Input/InputHandler.s"
	@echo "... src/Logic/AnimatedObject.o"
	@echo "... src/Logic/AnimatedObject.i"
	@echo "... src/Logic/AnimatedObject.s"
	@echo "... src/Logic/GameScene.o"
	@echo "... src/Logic/GameScene.i"
	@echo "... src/Logic/GameScene.s"
	@echo "... src/Logic/Interactable.o"
	@echo "... src/Logic/Interactable.i"
	@echo "... src/Logic/Interactable.s"
	@echo "... src/Logic/MainMenuScene.o"
	@echo "... src/Logic/MainMenuScene.i"
	@echo "... src/Logic/MainMenuScene.s"
	@echo "... src/Logic/MoveableObject.o"
	@echo "... src/Logic/MoveableObject.i"
	@echo "... src/Logic/MoveableObject.s"
	@echo "... src/Logic/MultiplayerClass.o"
	@echo "... src/Logic/MultiplayerClass.i"
	@echo "... src/Logic/MultiplayerClass.s"
	@echo "... src/Logic/Object.o"
	@echo "... src/Logic/Object.i"
	@echo "... src/Logic/Object.s"
	@echo "... src/Logic/Player.o"
	@echo "... src/Logic/Player.i"
	@echo "... src/Logic/Player.s"
	@echo "... src/Logic/Projectile.o"
	@echo "... src/Logic/Projectile.i"
	@echo "... src/Logic/Projectile.s"
	@echo "... src/Logic/Structure.o"
	@echo "... src/Logic/Structure.i"
	@echo "... src/Logic/Structure.s"
	@echo "... src/Renderer/Animator.o"
	@echo "... src/Renderer/Animator.i"
	@echo "... src/Renderer/Animator.s"
	@echo "... src/Renderer/FontManager.o"
	@echo "... src/Renderer/FontManager.i"
	@echo "... src/Renderer/FontManager.s"
	@echo "... src/Window/Game.o"
	@echo "... src/Window/Game.i"
	@echo "... src/Window/Game.s"
	@echo "... src/Window/Window.o"
	@echo "... src/Window/Window.i"
	@echo "... src/Window/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

